pipeline {
  agent any
  stages {
    stage('Stage1') {
      steps {
        sh 'echo "This is build $BUILD_NUMBER for jenkinstest pipeline"'
      }
    }
    stage('apply') {
      steps {
        sh "oc start-build jsonvalidator-bc"
      }
    }

  }
}