pipeline {
  agent any
  stages {
    stage('Stage1') {
      steps {
        sh 'echo "This is build $BUILD_NUMBER for jenkinstest pipeline"'
      }
    }
    stage('rebuild') {
      steps {
        sh "oc start-build jsonvalidator-bc"
      }
    }
    stage('Ask for input') {
        input {
            message 'Deploy?'
            ok 'Lets go!'
            parameters {
            string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
            }
        }
        steps {
            echo "scaling down and back up"
            sh '''
                oc scale --replicas=0 deployment/jsonvalidator-deployment
                oc scale --replicas=1 deployment/jsonvalidator-deployment
            '''
        }
    }
  }
}